source 'https://rubygems.org'

gem 'bcrypt'
gem 'faker'
gem 'letter_opener'
gem 'nifty_services', '~> 0.0.5'
gem 'pony'
gem 'pry'
gem 'rake'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sqlite3'
